[package]
name = "octo-chainsaw"
version = "0.1.0"
edition = "2021"
authors = ["danit595"]
description = "A Windows-based autoclicker application with a native GUI"

[dependencies]
native-windows-gui = "1.0.13"
native-windows-derive = "1.0.5"
winapi = { version = "0.3.9", features = ["winuser"] }
